apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-wedding
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
  - secretName: nebbia-tls
    hosts:
    - mobile-wedding.nebbia.io
  rules:
  - host: mobile-wedding.nebbia.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile-wedding
            port:
              number: 8000
